routes/admin.php
<?php

Route::get('admin/sign-in', ['uses' => 'Admin\Auth\LoginController@getLogin', 'as' => 'admin.login']);
Route::post('admin/sign-in', 'Admin\Auth\LoginController@postLogin');

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'auth:admin'], function () {
    Route::get('logout', ['uses' => 'Auth\LoginController@logout', 'as' => 'admin.logout']);
    Route::post('changePassword', 'Auth\AdminController@changePassword');

    Route::get('categories/childs', ['uses' => 'CategoryController@childs', 'as' => 'categories.childs']);
    Route::resource('categories', 'CategoryController')->except(['create', 'show']);
    Route::resource('tags', 'TagController')->except(['show']);
    Route::resource('advertisements','AdvertisementController')->except(['create','show']);
    Route::resource('films', 'FilmController');
    Route::get('films/{slug}/watch', 'FilmController@watchFilm');
    Route::resource('actors','ActorController');
    Route::resource('directors', 'DirectorController');

    // Route dashboard
    Route::get('dashboard', 'DashboardController@index')->name('dashboard.index');
    Route::get('dashboard/mostview', 'DashboardController@mostFilmView');
    Route::get('dashboard/viewedmonth', 'DashboardController@viewedFilmByMonth');
    Route::get('dashboard/viewbybrowser', 'DashboardController@reportViewedByBrowser');
    Route::get('dashboard/viewbydevice', 'DashboardController@reportViewedByDevice');
    Route::get('dashboard/viewedinmonth',['as'=>'viewedInMonth','uses'=>'DashboardController@viewedFilmInMonth']);

    Route::resource('trailers','TrailerController')->except(['create','show']);
    Route::resource('users','UserController');
    Route::resource('comments','CommentController');
    Route::resource('episodes','EpisodeController');

    Route::get('media-management', ['as' => 'mediashow', 'uses' => 'MediaController@index']);
    Route::delete('mediaremove/{id}', ['as' => 'media.deletefile', 'uses' => 'MediaController@destroy']);
    Route::delete('mediasremove', 'MediaController@deleteManyImage')->name('media.deletefiles');

    Route::resource('global-setting', 'GlobalSettingController');
});

routes/frontend.php
<?php

Route::group(['namespace' => 'FrontEnd'], function () {
	Route::get('/', ['as' => 'front-end.index', 'uses' => 'FrontEndController@homePage']);

	Route::get('sign-up', ['as' => 'front-end.sign-up', 'uses' => 'FrontEndController@getSignUp']);
	Route::post('sign-up', ['as' => 'front-end.sign-up', 'uses' => 'FrontEndController@postSignUp']);
	Route::get('login', ['as' => 'front-end.login', 'uses' => 'LoginController@getLogin']);
	Route::post('login', ['as' => 'front-end.login', 'uses' => 'LoginController@postLogin']);

	Route::group(['middleware' => ['auth:user']], function () {
		Route::get('profile', ['as' => 'front-end.profile', 'uses' => 'FrontEndController@showProfile']);
		Route::post('changepassword', 'LoginController@changepassword');
		Route::get('logout', ['as' => 'front-end.logout', 'uses' => 'LogoutController@getLogout']);
	});

	Route::get('the-loai/{slug}', ['as' => 'front-end.genres', 'uses' => 'FrontEndController@getFilmsByGenres']);
	Route::get('quoc-gia/{slug}', ['as' => 'front-end.countries', 'uses' => 'FrontEndController@getFilmsByGenres']);
	Route::get('{slug}', ['as' => 'front-end.films', 'uses' => 'FrontEndController@getFilmsByGenres']);
	Route::get('phim-le/{slug}', ['as' => 'front-end.filmsodd', 'uses' => 'FrontEndController@getFilmsByGenres']);
	Route::get('phim-bo/{slug}', ['as' => 'front-end.filmsseries', 'uses' => 'FrontEndController@getFilmsByGenres']);
	Route::get('phim/{slug}', ['as' => 'front-end.filminfo', 'uses' => 'FrontEndController@getFilmsInfo']);
	Route::get('phim/{slug}/xem-phim.html',['as' => 'front-end.watch', 'uses' => 'FrontEndController@watchFilm']);
	Route::get('phim/tap/{slug}/xem-phim.html', ['as' => 'front-end.episode', 'uses' => 'FrontEndController@episodeOfFilm']);
	Route::get('ho-so/dao-dien/{slug}', ['as' => 'director.profile', 'uses' => 'FrontEndController@getDirectorProfile']);
	Route::get('ho-so/dien-vien/{slug}', ['as' => 'actor.profile', 'uses' => 'FrontEndController@getActorProfile']);
	Route::any('tim-kiem', ['as' => 'search', 'uses' => 'FrontEndController@getSearch']);

}); 

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => '', 'namespace' => 'V1'], function () {
    require(base_path('routes/admin.php'));
});

Route::group(['prefix' => '', 'namespace' => 'V1'], function () {
    require(base_path('routes/frontend.php'));
});

Route::get('user/testing', function(){
	return view('frontends.pages.login');
});
Route::get('user/register', function(){
	return view('frontends.pages.register');
});
Route::get('user/profile', function(){
	return view('frontends.pages.user-profile');
});

app/Models/GlobalSetting.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;
use Cviebrock\EloquentSluggable\SluggableScopeHelpers;

class GlobalSetting extends Model
{
    use Sluggable, SluggableScopeHelpers;

    protected $fillable = [
        'company_name',
        'company_phone',
        'company_email',
        'company_facebook',
        'company_youtube',
        'company_googleplus',
        'company_address',
        'company_copyright',
    ];

    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'company_name'
            ]
        ];
    }
}

app/Http/Controllers/V1/Admin/GlobalSettingController.php
<?php

namespace App\Http\Controllers\V1\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\V1\Admin\GlobalSetting\StoreRequest;
use App\Http\Requests\V1\Admin\GlobalSetting\UpdateRequest;
use App\Repositories\GlobalSetting\GlobalSettingRepositoryInterface;

class GlobalSettingController extends Controller
{

    protected $globalSettingRepository;

    public function __construct(GlobalSettingRepositoryInterface $globalSettingRepository)
    {
        $this->globalSettingRepository = $globalSettingRepository;
        $this->data['globalSetting'] = $this->globalSettingRepository->all()->first();
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.contents.globalsettings.index', $this->data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRequest $request)
    {
        try {
            if(count($this->globalSettingRepository->all()) >= 1) {
                return redirect()->route( 'global-setting.index')->with('status_w', 'Đã tồn tại thông tin cho website');
            } else {
                $data['company_name'] = $request['name'];
                $data['company_phone'] = $request['phone'];
                $data['company_email'] = $request['email'];
                $data['company_facebook'] = $request['facebook'];
                $data['company_youtube'] = $request['youtube'];
                $data['company_googleplus'] = $request['google'];
                $data['company_address'] = $request['address'];
                $data['company_copyright'] = $request['copyright'];
                $this->globalSettingRepository->create($data);
                return redirect()->back()->with('status_s', 'Đã lưu thông tin cho website');  
            }
        } catch(\Throwable $th) {
            return redirect()->route('global-setting.index')->with('status_d', 'Đã có lỗi xảy ra, không thể lưu.');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($slug)
    {
        try {
            $this->data['global'] = $this->globalSettingRepository->findBySlugOrFail($slug);
            return view('admin.contents.globalsettings.index', $this->data);
        } catch (\Throwable $th) {
            return view('admin.errors.404');
        }
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRequest $request, $slug)
    {
        try {
            $global = $this->globalSettingRepository->findBySlugOrFail($slug);
            $data = [
                'company_name' => $request['name'],
                'slug' => str_slug($request['name']),
                'company_phone' => $request['phone'],
                'company_email' => $request['email'],
                'company_facebook' => $request['facebook'],
                'company_youtube' => $request['youtube'],
                'company_googleplus' => $request['google'],
                'company_address' => $request['address'],
                'company_copyright' => $request['copyright'],
            ];
            $this->globalSettingRepository->update($data, $slug);
            return redirect()->route('global-setting.index')->with('status_s', 'Đã lưu chỉnh sửa thông tin cho website');
        } catch (\Throwable $th) {
            return redirect()->back()->with('status_d', 'Đã có lỗi xảy ra, không thể lưu.');
        }
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/contents/globalsettings/create.blade.php
@if (isset($global))
    {!! Form::model($global,array('route' => array('global-setting.update',$global->slug),'method' => 'PUT')) !!}
@else
    {!! Form::open(array('url' => 'admin/global-setting', 'method' => 'POST')) !!} 
@endif
{!! csrf_field() !!}
<div class="container mt-5">
    <div class="form-group border-0 shadow">
        <div class="card">
            <div class="card-header bg-dark text-white text-uppercase font-weight-bold">
                {{ isset($global) ? 'Cập nhật ' : '' }}Thông tin website
            </div>
            <div class="card-body">
                <div class="container">
                    <div class="form-group required">
                        {!! Form::label('name', 'Tên website ( công ty )', ['class' => 'font-weight-bold']) !!} 
                        {!! Form::text('name',isset($global) ? $global->company_name : '', ['class' => $errors->has('name') ? 'form-control error' : 'form-control']) !!}
                        <span class="text-danger">{{ $errors->first('name') }}</span>
                    </div>
                    <div class="form-group">
                        {!! Form::label('phone', 'Số điện thoai', ['class' => 'font-weight-bold']) !!} 
                        {!! Form::tel('phone', isset($global) ? $global->company_phone : '', ['class' => $errors->has('phone') ? 'form-control error' : 'form-control', 'maxlength' => '12']) !!}
                        <span class="text-danger">{{ $errors->first('phone') }}</span>
                    </div>
                    <div class="form-group">
                        {!! Form::label('email', 'E-mail', ['class' => 'font-weight-bold']) !!} 
                        {!! Form::text('email', isset($global) ? $global->company_email : '', ['class' => $errors->has('email') ? 'form-control error' : 'form-control']) !!}
                        <span class="text-danger">{{ $errors->first('email') }}</span>
                    </div>
                    <div class="form-group">
                        {!! Form::label('facebook', 'Link Facebook', ['class' => 'font-weight-bold']) !!} 
                        {!! Form::text('facebook', isset($global) ? $global->company_facebook : '', ['class' => $errors->has('facebook') ? 'form-control error' : 'form-control']) !!}
                        <span class="text-danger">{{ $errors->first('facebook') }}</span>
                    </div>
                    <div class="form-group">
                        {!! Form::label('youtube', 'Link Youtube', ['class' => 'font-weight-bold']) !!} 
                        {!! Form::text('youtube', isset($global) ? $global->company_youtube : '', ['class' => $errors->has('youtube') ? 'form-control error' : 'form-control']) !!}
                        <span class="text-danger">{{ $errors->first('youtube') }}</span>
                    </div>
                    <div class="form-group">
                        {!! Form::label('google', 'Link Google plus', ['class' => 'font-weight-bold']) !!} 
                        {!! Form::text('google', isset($global) ? $global->company_googleplus : '', ['class' => $errors->has('google') ? 'form-control error' : 'form-control']) !!}
                        <span class="text-danger">{{ $errors->first('google') }}</span>
                    </div>
                    <div class="form-group">
                        {!! Form::label('address', 'Địa chỉ website ( Công ty )', ['class' => 'font-weight-bold']) !!} 
                        {!! Form::text('address', isset($global) ? $global->company_address : '', ['class' => $errors->has('address') ? 'form-control error' : 'form-control']) !!}
                        <span class="text-danger">{{ $errors->first('address') }}</span>
                    </div>
                    <div class="form-group required">
                        {!! Form::label('copyright', 'Copyright', ['class' => 'font-weight-bold']) !!} 
                        {!! Form::text('copyright', isset($global) ? $global->company_copyright : '', ['class' => $errors->has('coppright') ? 'form-control error' : 'form-control']) !!}
                        <span class="text-danger">{{ $errors->first('copyright') }}</span>
                    </div>
                    <div class="form-group">
                        {!! Form::submit('Lưu thông tin', ['class' => 'btn btn-success border-0 shadow b-r-xs']) !!}
                        @if (isset($global))
                            <a href="{{ route('global-setting.index') }}" class="btn btn-dark b-r-xs ml-3">Hủy</a>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{!! Form::close() !!}

resources/views/admin/contents/globalsettings/index.blade.php
@extends('admin.layouts.master') 
@section('title','Quản lý danh mục') 
@section('content')
    <div class="form-group row bg-white pb-4">
        <div class="col-md-12 position-alert">
            @include('admin.includes.alert')
        </div>
        <div class="col-md-7">
            @include('admin.contents.globalsettings.info')
        </div>
        <div class="col-md-5">
            @include('admin.contents.globalsettings.create')
        </div>
    </div>
@endsection

resources/views/admin/contents/globalsettings/info.blade.php
<div class="container mt-5">
    <div class="form-group border-0 shadow">
        <div class="card">
            <div class="card-header bg-dark text-center text-white text-uppercase font-weight-bold">
                Hiển thị thông tin website
            </div>
            <div class="card-body pl-0 pr-0">
                <div class="container-fluid">
                    <div class="form-group">
                        {!! Form::label('company_name', 'Tên Công Ty', ['class' => 'font-weight-bold']) !!}
                        <p><i class="far fa-hand-point-right text-danger"></i> <span class="text-primary"> {{ $globalSetting->company_name }}</span></p>
                    </div>
                    <div class="form-group">
                        {!! Form::label('company_phone', 'Số điện thoại liên hệ', ['class' => 'font-weight-bold']) !!}
                        <p><i class="far fa-hand-point-right text-danger"></i> <span class="text-primary"> {{ $globalSetting->company_phone }}</span></p>
                    </div>
                    <div class="form-group">
                        {!! Form::label('company_email', 'Email Công Ty', ['class' => 'font-weight-bold']) !!}
                        <p><i class="far fa-hand-point-right text-danger"></i> <span class="text-primary"> {{ $globalSetting->company_email }}</span></p>
                    </div>
                    <div class="form-group">
                        {!! Form::label('company_facebook', 'Link Facebook của Công Ty', ['class' => 'font-weight-bold']) !!}
                        <p><i class="far fa-hand-point-right text-danger"></i> <span class="text-primary"> {{ $globalSetting->company_facebook }}</span></p>
                    </div>
                    <div class="form-group">
                        {!! Form::label('company_youtube', 'Link Youtube của Công Ty', ['class' => 'font-weight-bold']) !!}
                        <p><i class="far fa-hand-point-right text-danger"></i> <span class="text-primary"> {{ $globalSetting->company_youtube }}</span></p>
                    </div>
                    <div class="form-group">
                        {!! Form::label('company_googleplus', 'Link Google Plus của Công Ty', ['class' => 'font-weight-bold']) !!}
                        <p><i class="far fa-hand-point-right text-danger"></i> <span class="text-primary"> {{ $globalSetting->company_googleplus }}</span></p>
                    </div>
                    <div class="form-group">
                        {!! Form::label('company_address', 'Địa chỉ liên hệ của Công Ty', ['class' => 'font-weight-bold']) !!}
                        <p><i class="far fa-hand-point-right text-danger"></i> <span class="text-primary"> {{ $globalSetting->company_address }}</span></p>
                    </div>
                    <div class="form-group">
                        {!! Form::label('company_copyright', 'Thông tin Copyright', ['class' => 'font-weight-bold']) !!}
                        <p><i class="far fa-hand-point-right text-danger"></i> <span class="text-primary"> {{ $globalSetting->company_copyright }}</span></p>
                    </div>
                    <hr>
                    <div class="form-group">    
                        <div class="float-left">
                            <a class="btn btn-primary b-r-xs" href="{{ route('global-setting.edit', $globalSetting->slug) }}">Cập nhật lại thông tin</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>