routes/admin.php
<?php

Route::get('admin/sign-in', ['uses' => 'Admin\Auth\LoginController@getLogin', 'as' => 'admin.login']);
Route::post('admin/sign-in', 'Admin\Auth\LoginController@postLogin');

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'auth:admin'], function () {
    Route::get('logout', ['uses' => 'Auth\LoginController@logout', 'as' => 'admin.logout']);
    Route::post('changePassword', 'Auth\AdminController@changePassword');

    Route::get('categories/childs', ['uses' => 'CategoryController@childs', 'as' => 'categories.childs']);
    Route::resource('categories', 'CategoryController')->except(['create', 'show']);
    Route::resource('tags', 'TagController')->except(['show']);
    Route::resource('advertisements','AdvertisementController')->except(['create','show']);
    Route::resource('films', 'FilmController');
    Route::get('films/{slug}/watch', 'FilmController@watchFilm');
    Route::resource('actors','ActorController');
    Route::resource('directors', 'DirectorController');

    // Route dashboard
    Route::get('dashboard', 'DashboardController@index')->name('dashboard.index');
    Route::get('dashboard/mostview', 'DashboardController@mostFilmView');
    Route::get('dashboard/viewedmonth', 'DashboardController@viewedFilmByMonth');
    Route::get('dashboard/viewbybrowser', 'DashboardController@reportViewedByBrowser');
    Route::get('dashboard/viewbydevice', 'DashboardController@reportViewedByDevice');
    Route::get('dashboard/viewedinmonth',['as'=>'viewedInMonth','uses'=>'DashboardController@viewedFilmInMonth']);

    Route::resource('trailers','TrailerController')->except(['create','show']);
    Route::resource('users','UserController');
    Route::resource('comments','CommentController');
    Route::resource('episodes','EpisodeController');

    Route::get('media-management', ['as' => 'mediashow', 'uses' => 'MediaController@index']);
    Route::delete('mediaremove/{id}', ['as' => 'media.deletefile', 'uses' => 'MediaController@destroy']);
    Route::delete('mediasremove', 'MediaController@deleteManyImage')->name('media.deletefiles');

    Route::resource('global-setting', 'GlobalSettingController');
});

routes/frontend.php
<?php

Route::group(['namespace' => 'FrontEnd'], function () {
	Route::get('/', ['as' => 'front-end.index', 'uses' => 'FrontEndController@homePage']);

	Route::get('sign-up', ['as' => 'front-end.sign-up', 'uses' => 'FrontEndController@getSignUp']);
	Route::post('sign-up', ['as' => 'front-end.sign-up', 'uses' => 'FrontEndController@postSignUp']);
	Route::get('login', ['as' => 'front-end.login', 'uses' => 'LoginController@getLogin']);
	Route::post('login', ['as' => 'front-end.login', 'uses' => 'LoginController@postLogin']);

	Route::group(['middleware' => ['auth:user']], function () {
		Route::get('profile', ['as' => 'front-end.profile', 'uses' => 'FrontEndController@showProfile']);
		Route::post('changepassword', 'LoginController@changepassword');
		Route::get('logout', ['as' => 'front-end.logout', 'uses' => 'LogoutController@getLogout']);
	});

	Route::get('the-loai/{slug}', ['as' => 'front-end.genres', 'uses' => 'FrontEndController@getFilmsByGenres']);
	Route::get('quoc-gia/{slug}', ['as' => 'front-end.countries', 'uses' => 'FrontEndController@getFilmsByGenres']);
	Route::get('{slug}', ['as' => 'front-end.films', 'uses' => 'FrontEndController@getFilmsByGenres']);
	Route::get('phim-le/{slug}', ['as' => 'front-end.filmsodd', 'uses' => 'FrontEndController@getFilmsByGenres']);
	Route::get('phim-bo/{slug}', ['as' => 'front-end.filmsseries', 'uses' => 'FrontEndController@getFilmsByGenres']);
	Route::get('phim/{slug}', ['as' => 'front-end.filminfo', 'uses' => 'FrontEndController@getFilmsInfo']);
	Route::get('phim/{slug}/xem-phim.html',['as' => 'front-end.watch', 'uses' => 'FrontEndController@watchFilm']);
	Route::get('phim/tap/{slug}/xem-phim.html', ['as' => 'front-end.episode', 'uses' => 'FrontEndController@episodeOfFilm']);
	Route::get('ho-so/dao-dien/{slug}', ['as' => 'director.profile', 'uses' => 'FrontEndController@getDirectorProfile']);
	Route::get('ho-so/dien-vien/{slug}', ['as' => 'actor.profile', 'uses' => 'FrontEndController@getActorProfile']);
	Route::any('tim-kiem', ['as' => 'search', 'uses' => 'FrontEndController@getSearch']);

}); 

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => '', 'namespace' => 'V1'], function () {
    require(base_path('routes/admin.php'));
});

Route::group(['prefix' => '', 'namespace' => 'V1'], function () {
    require(base_path('routes/frontend.php'));
});

Route::get('user/testing', function(){
	return view('frontends.pages.login');
});
Route::get('user/register', function(){
	return view('frontends.pages.register');
});
Route::get('user/profile', function(){
	return view('frontends.pages.user-profile');
});

resources/views/admin/includes/alert.blade.php
@if (session('status_s') )
    <div class="positon-info col-md-3">
        <ul>
            <li id="notification-alert" class="alert alert-success alert-dismissible fade show" role="alert">
                <a class="nav-item font-weight-bold">{{ session('status_s') }}</a>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </li>
        </ul>
    </div>
@elseif(session('status_w'))
    <div class="positon-info col-md-3">
        <ul>
            <li id="notification-alert" class="alert alert-warning alert-dismissible fade show" role="alert">
                <a class="nav-item font-weight-bold">{{ session('status_w') }}</a>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </li>
        </ul>
    </div>
@elseif(session('status_d'))
    <div class="positon-info col-md-3">
        <ul>
            <li id="notification-alert" class="alert alert-danger alert-dismissible fade show" role="alert">
                <a class="nav-item font-weight-bold">{{ session('status_d') }}</a>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </li>
        </ul>
    </div>
@elseif(session('status_i'))
    <div class="positon-info col-md-3">
        <ul>
            <li id="notification-alert" class="alert alert-info alert-dismissible fade show" role="alert">
                <a class="nav-item font-weight-bold">{{ session('status_i') }}</a>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </li>
        </ul>
    </div>
@elseif(session('status_p'))
    <div class="positon-info col-md-3">
        <ul>
            <li id="notification-alert" class="alert alert-primary alert-dismissible fade show" role="alert">
                <a class="nav-item font-weight-bold">{{ session('status_p') }}</a>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </li>
        </ul>
    </div>
@endif

resources/views/admin/includes/footer.blade.php
<div>
    <strong>Copyright</strong> Dphim &copy; 2015 - {{date('Y')}}
</div>

resources/views/admin/includes/navbartop.blade.php
<div class="row border-bottom">
    <nav class="navbar navbar-static-top {{ !empty($__env->yieldContent('page-heading')) ? '' : 'white-bg' }} " role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
        </div>
        @if (Auth::guard('admin')->check())
        <ul class="nav navbar-top-links navbar-right">
            <li class="dropdown">
                <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                    <span class="m-r-sm text-muted welcome-message">Xin chào, <span class="text-info font-weight-bold">{{ Auth::guard('admin')->user()->first_name ." ". Auth::guard('admin')->user()->last_name }} <b class="caret"></b></span></span>
                </a>
                <ul class="dropdown-menu animated fadeInRight m-t-xs">
                    <li><a class="dropdown-item" href="#" data-toggle="modal" data-target="#changePassword">Thay đổi mật khẩu</a></li>
                    <li class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="{{ route('admin.logout') }}">Đăng xuất</a></li>
                </ul>
            </li>
            <li>
                <a href="{{ route('admin.logout') }}">
                    <i class="fas fa-sign-out-alt"></i>Đăng xuất
                </a>
            </li>
        </ul>
        @endif
    </nav>
</div>
@include('admin.modals.admins.change_password')

resources/views/admin/includes/slidebar.blade.php
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <h2><span class="block m-t-xs font-bold text-uppercase"><i class="fa fa-film" aria-hidden="true"></i> Dphim</span></h2>
                    </a>
                </div>
                <div class="logo-element">
                    <i class="fa fa-film" style='font-size:28px' aria-hidden="true"></i>
                </div>
            </li>
            <li>
                <a href="{{ route('dashboard.index') }}"><i class="fa fa-home"></i> <span class="nav-label">Dashboards</span></a>
            </li>
            <li>
                <a href="#"><i class="fa fa-th-list"></i> <span class="nav-label">Quản lý danh mục</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse">
                    <li><a href="{{ route('categories.index') }}">Tạo danh mục chính</a></li>
                    <li><a href="{{ route('categories.childs') }}">Tạo danh mục phụ</a></li>
                </ul>
            </li>
            <li>
                <a href="#"><i class="fas fa-tag"></i> <span class="nav-label">Quản lý tags</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse">
                    <li><a href="{{ route('tags.create') }}">Tạo tags mới</a></li>
                    <li><a href="{{ route('tags.index') }}">Danh sách tags</a></li>
                </ul>
            </li>
            <li>
                <a href="#"><i class="far fa-id-card"></i> <span class="nav-label">Diễn viên / Đạo diễn</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse">
                    <li><a href="{{ route('actors.create') }}">Thêm mới</a></li>
                    <li><a href="{{ route('actors.index') }}">Danh sách</a></li>
                </ul>
            </li>
            <li>
                <a href="#"><i class="fa fa-ad"></i> <span class="nav-label">Quản lý quảng cáo</span><span
                        class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse">
                    <li><a href="{{ route('advertisements.index') }}">Tạo quảng cáo</a></li>
                </ul>
            </li>
            <li>
                <a href="{{ route('trailers.index') }}"><i class="fa fa-video"></i> <span class="nav-label">Quản lý trailer</span></a>
            </li>
            <li>
                <a href="{{ route('episodes.index') }}"><i class="fab fa-youtube"></i> <span class="nav-label">Quản lý tập phim</span></a>
            </li>
            <li>
                <a href="#"><i class="fas fa-film"></i> <span class="nav-label">Quản lý phim</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse">
                    <li><a href="{{ route('films.create') }}">Thêm phim mới</a></li>
                    <li><a href="{{ route('films.index') }}">Danh sách phim</a></li>
                </ul>
            </li>
            <li>
                <a href="{{ route('users.index') }}"><i class="fa fa-user"></i> <span class="nav-label">Quản lý user</span></a>
            </li>
            <li>
                <a href="{{ route('comments.index') }}"><i class="fa fa-comment"></i> <span class="nav-label">Quản lý bình luận</span></a>
            </li>
            <li>
                <a href="#"><i class="far fa-images"></i> <span class="nav-label">Quản lý thư viện ảnh</span><span
                        class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse">
                    <li><a href="{{ route('mediashow') }}">Tất cả ảnh</a></li>
                </ul>
            </li>
            <li>
                <a href="{{ route('global-setting.index') }}"><i class="fas fa-blog"></i> <span class="nav-label">Quản lý thông tin website</span></a>
            </li>
        </ul>
    </div>
</nav>